import React, {useRef, useState} from 'react';
import {downloadCSV, validateFiles, MAX_BATCH_MB} from './utils.js';

const API = (import.meta.env.VITE_API_URL || '').replace(/\/$/,'');
const skillOptions = ['python','javascript','typescript','react','node.js','fastapi','django','flask','sql','postgresql','mongodb','docker','git','aws','azure','machine learning','deep learning','nlp','java','c++','c#','html','css','excel','power bi','tableau','kubernetes','linux'];
const Icon = ({name,size=20,...props}) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{({grid:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,doc:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></>,upload:<><path d="M12 16V3m-5 5 5-5 5 5M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5"/></>,check:<path d="m5 12 4 4L19 6"/>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,download:<><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></>,close:<path d="m6 6 12 12M6 18 18 6"/>,star:<path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9Z"/>,moon:<path d="M21 13a9 9 0 1 1-10-10 7 7 0 0 0 10 10Z"/>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/></>,trash:<><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/></>,menu:<path d="M3 6h18M3 12h18M3 18h18"/>})[name]}</svg>;

async function apiRequest(path,body,signal) {
  let response;
  try {response = await fetch(API + path,{method:'POST',body,signal});}
  catch(error) {if(error.name==='AbortError') throw error; throw new Error('Cannot connect to the backend. Start FastAPI on port 8000 and try again.');}
  const data = await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(typeof data.detail==='string'?data.detail:'The request failed. Check the files and try again.');
  return data;
}
const Tags = ({items,missing=false}) => <div className="tags">{items.length?items.map(s=><span className={'tag '+(missing?'missing':'')} key={s}>{s}</span>):<span className="muted">None detected</span>}</div>;

export default function App(){
 const [theme,setTheme]=useState('dark'),[menu,setMenu]=useState(false),[view,setView]=useState('workspace');
 const [jd,setJd]=useState(''),[required,setRequired]=useState([]),[custom,setCustom]=useState(''),[method,setMethod]=useState('skills');
 const [files,setFiles]=useState([]),[drag,setDrag]=useState(false),[busy,setBusy]=useState(false),[suggesting,setSuggesting]=useState(false),[error,setError]=useState('');
 const [results,setResults]=useState(null),[shortlist,setShortlist]=useState([]),[query,setQuery]=useState(''),[minimum,setMinimum]=useState(0),[sort,setSort]=useState('rank');
 const [display,setDisplay]=useState('cards'),[selected,setSelected]=useState(null),[dirty,setDirty]=useState(false);
 const uploadRef=useRef(null),controller=useRef(null),suggestController=useRef(null),requestVersion=useRef(0);
 const candidates=results?.candidates||[];
 const visible=candidates.filter(r=>(view!=='shortlist'||shortlist.includes(r.id))&&r.name.toLowerCase().includes(query.toLowerCase())&&(r.coverage==null||r.coverage>=minimum));
 if(sort==='coverage')visible.sort((a,b)=>(b.coverage??-1)-(a.coverage??-1));
 if(sort==='name')visible.sort((a,b)=>a.name.localeCompare(b.name));
 const selectedRow=candidates.find(r=>r.id===selected);
 const toggleSkill=s=>{setRequired(prev=>prev.includes(s)?prev.filter(x=>x!==s):[...prev,s]);setDirty(true);};
 const addCustom=()=>{const values=custom.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);setRequired(prev=>[...new Set([...prev,...values])]);setCustom('');setDirty(true);};
 const addFiles=incoming=>{const combined=[...files,...Array.from(incoming)];const issue=validateFiles(combined);if(issue){setError(issue);return;}setFiles(combined);setError('');setDirty(true);};
 const suggest=async()=>{if(!jd.trim()){setError('Enter a job description first.');return;}const version=requestVersion.current;const abort=new AbortController();suggestController.current=abort;setSuggesting(true);setError('');try{const data=new FormData();data.append('job_description',jd);const response=await apiRequest('/api/suggest-skills',data,abort.signal);if(version===requestVersion.current){setRequired(prev=>[...new Set([...prev,...response.skills])]);setDirty(true);}}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{if(version===requestVersion.current)setSuggesting(false);}};
 const compare=async()=>{const issue=validateFiles(files);if(!jd.trim()||!files.length){setError('Add a job description and at least one resume.');return;}if(issue){setError(issue);return;}if(method==='skills'&&!required.length){setError('Choose at least one required skill.');return;}setBusy(true);setError('');const abort=new AbortController();controller.current=abort;const version=requestVersion.current;try{const body=new FormData();body.append('job_description',jd);body.append('required_skills',required.join(','));body.append('method',method);files.forEach(f=>body.append('files',f));const response=await apiRequest('/api/screen',body,abort.signal);if(version===requestVersion.current){setResults(response);setShortlist([]);setSelected(null);setDirty(false);setView('workspace');setQuery('');setMinimum(0);setSort('rank');}}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{if(version===requestVersion.current)setBusy(false);}};
 const clear=()=>{requestVersion.current++;controller.current?.abort();suggestController.current?.abort();setFiles([]);setJd('');setRequired([]);setResults(null);setShortlist([]);setSelected(null);setError('');setCustom('');setQuery('');setMinimum(0);setBusy(false);setSuggesting(false);setDirty(false);};
 const toggleShortlist=id=>setShortlist(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
 const best=candidates.length?Math.max(...candidates.map(r=>r.coverage??0)):null;
 return <div className={'app '+theme}>
   <aside className={'sidebar '+(menu?'open':'')}>
    <button className="icon-button sidebar-close" aria-label="Close navigation" onClick={()=>setMenu(false)}><Icon name="close"/></button>
    <a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-mark"><Icon name="doc"/></span>Resume<span>Studio</span><small>2.0</small></a>
    <div className="nav-label">WORKSPACE</div>
    <nav aria-label="Main navigation">{[['workspace','grid','Overview'],['shortlist','star','My shortlist']].map(([id,icon,label])=><button className={'nav-item '+(view===id?'active':'')} onClick={()=>{setView(id);setMenu(false);}} key={id}><Icon name={icon}/>{label}{id==='shortlist'&&<span className="nav-count">{shortlist.length}</span>}</button>)}</nav>
    <div className="sidebar-card"><span className="status-dot"/> SESSION WORKSPACE<p>Documents stay in this session. Clear your workspace when you’re finished.</p><button className="text-button" onClick={clear}><Icon name="trash" size={15}/>Clear workspace</button></div>
    <div className="sidebar-bottom"><div className="avatar">S</div><div><strong>Your workspace</strong><span>Resume review</span></div><button className="icon-button" aria-label={'Switch to '+(theme==='dark'?'light':'dark')+' theme'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name={theme==='dark'?'sun':'moon'}/></button></div>
   </aside>
   {menu&&<button className="backdrop" aria-label="Dismiss navigation overlay" onClick={()=>setMenu(false)}/>}
   <main>
    <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMenu(true)}><Icon name="menu"/></button>Workspace <span>/</span><strong>{view==='workspace'?'Overview':'Shortlist'}</strong></div><span className="top-note"><span className="status-dot"/> Human-led review</span></header>
    <section className="hero">
     <div className="hero-copy"><div className="eyebrow"><span>✦</span> A CLEARER WAY TO REVIEW TALENT</div><h1>Your next great team.<br/><span>Starts with the right shortlist.</span></h1><p>Bring every resume into focus. Compare job requirements, explore the evidence, and keep promising candidates in one place.</p><div className="hero-steps"><span><b>01</b> Define your role</span><span><b>02</b> Add resumes</span><span><b>03</b> Review candidates</span></div></div>
     <div className="hero-art" aria-hidden="true"><div className="art-orbit one"/><div className="art-orbit two"/><div className="floating-dot"/><div className="paper back"/><div className="paper front"><div className="paper-avatar"/><div className="paper-line short"/><div className="paper-line"/><div className="paper-line"/><div className="paper-tags"><i/><i/><i/></div><div className="paper-line short"/></div><div className="art-badge"><span><Icon name="check" size={16}/></span>Evidence-led review</div><span className="spark">✧</span></div>
    </section>
    <section className="metrics" aria-label="Workspace summary">{[['doc','Resumes compared',candidates.length,'In your latest batch'],['check','Required skills',results?.required.length??required.length,'Job-related criteria'],['star','Shortlisted',shortlist.length,'Selected for human review'],['grid','Best skill coverage',best==null?'—':best+'%','Detected required terms']].map(([icon,label,value,hint])=><div className="metric" key={label}><div className="metric-heading"><span>{label}</span><span className="metric-icon"><Icon name={icon} size={17}/></span></div><strong>{value}</strong><small>{hint}</small></div>)}</section>
    {error&&<div className="notice error" role="alert"><span>{error}</span><button className="icon-button" onClick={()=>setError('')} aria-label="Dismiss error"><Icon name="close" size={17}/></button></div>}
    {view==='workspace'&&<><div className="section-heading"><div><h2>Set up your screening</h2><p>A little context makes every comparison more useful.</p></div><span className="subtle-badge">PDF · DOCX · TXT</span></div>
    <div className="setup-grid"><section className="panel"><div className="panel-heading"><span className="step-number">01</span><div><h3>Define the role</h3><p>What does your next hire need to bring?</p></div></div>
     <label htmlFor="jd">Job description <span className="optional">Required</span></label><textarea id="jd" value={jd} disabled={busy} maxLength={20000} onChange={e=>{setJd(e.target.value);setDirty(true);}} placeholder="Paste the role, responsibilities, and required skills here…"/><div className="field-footer"><span>{jd.length.toLocaleString()} / 20,000</span><button className="text-button" disabled={suggesting||busy||!jd.trim()} onClick={suggest}>{suggesting?'Detecting…':'✦ Detect skills from description'}</button></div>
     <label>Required skills <span className="optional">{required.length} selected</span></label><div className="skill-picker">{[...new Set([...skillOptions,...required])].map(s=><button disabled={busy} aria-pressed={required.includes(s)} className={'skill-option '+(required.includes(s)?'selected':'')} key={s} onClick={()=>toggleSkill(s)}>{required.includes(s)&&<Icon name="check" size={12}/>} {s}</button>)}</div>
     <div className="custom-input"><input aria-label="Custom skills" disabled={busy} value={custom} maxLength={300} onChange={e=>setCustom(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addCustom();}}} placeholder="Add custom skills, separated by commas"/><button className="secondary-button" disabled={busy||!custom.trim()} onClick={addCustom}>Add</button></div>
    </section>
    <section className="panel upload-panel"><div className="panel-heading"><span className="step-number teal">02</span><div><h3>Add your candidates</h3><p>Bring the resumes. We’ll organise the evidence.</p></div></div>
     <input ref={uploadRef} type="file" multiple accept=".pdf,.docx,.txt" hidden onChange={e=>{addFiles(e.target.files);e.target.value='';}}/>
     <button disabled={busy} className={'dropzone '+(drag?'dragging':'')} onClick={()=>uploadRef.current.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)addFiles(e.dataTransfer.files);}}><span className="upload-icon"><Icon name="upload" size={28}/></span><strong>Drop your resumes here</strong><span>or <b>browse files</b> from your device</span><small>PDF, DOCX, TXT · {Math.min(10, MAX_BATCH_MB)} MB each · {MAX_BATCH_MB} MB per batch</small></button>
     <div className="upload-meta"><span>{files.length} documents added</span><span>Up to 50 resumes</span></div>
     {files.length>0&&<ul className="file-list">{files.map((f,i)=><li key={f.name+i}><span className="file-icon"><Icon name="doc" size={17}/></span><div><strong>{f.name}</strong><small>{(f.size/1024).toFixed(1)} KB</small></div><button disabled={busy} className="icon-button" aria-label={'Remove '+f.name} onClick={()=>{setFiles(prev=>prev.filter((_,n)=>n!==i));setDirty(true);}}><Icon name="close" size={16}/></button></li>)}</ul>}
     <div className="mode-picker"><label htmlFor="method">Comparison method</label><select disabled={busy} id="method" value={method} onChange={e=>{setMethod(e.target.value);setDirty(true);}}><option value="skills">Required skill coverage</option><option value="semantic">Skills + semantic similarity</option></select><p>{method==='skills'?'Checks selected terms and known aliases. No AI model download needed.':'Adds text similarity. Optional backend dependencies and a first-time model download are required.'}</p></div>
     <div className="tip"><Icon name="doc" size={18}/><span>Text-based PDFs work best. Scanned documents need OCR before uploading.</span></div>
    </section></div>
    <div className="action-bar"><div><strong>Ready to take a closer look?</strong><span>{files.length} resumes · {required.length} required skills</span></div><button className="primary-button" onClick={compare} disabled={busy||suggesting}>{busy?<><span className="spinner"/>Comparing resumes…</>:<>Compare resumes<Icon name="arrow"/></>}</button></div></>}
    <section className="results-section"><div className="section-heading"><div><h2>{view==='shortlist'?'Your shortlist':'Candidate workspace'}<span className="count-badge">{view==='shortlist'?shortlist.length:candidates.length}</span></h2><p>{view==='shortlist'?'The candidates you selected for a closer review.':'Inspect what matches, what’s missing, and what deserves a closer look.'}</p></div><button className="secondary-button" disabled={!visible.length} onClick={()=>downloadCSV(visible,shortlist,view==='shortlist'?'resume-shortlist.csv':'resume-comparison.csv')}><Icon name="download" size={16}/>Export CSV</button></div>
    {results&&dirty&&<div className="notice">Inputs have changed. Compare resumes again to refresh these results.</div>}
    {results?.issues.map((issue,i)=><div className="notice warning" key={i}>{issue.file&&<strong>{issue.file}: </strong>}{issue.message}</div>)}
    {candidates.length>0?<><div className="results-toolbar"><div className="search-input"><Icon name="search" size={18}/><input aria-label="Search candidates" placeholder="Search by filename…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-control"><label htmlFor="minimum">Coverage</label><select id="minimum" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}><option value="0">All scores</option><option value="50">50% or higher</option><option value="75">75% or higher</option><option value="100">100%</option></select></div><select aria-label="Sort candidates" value={sort} onChange={e=>setSort(e.target.value)}><option value="rank">Original ranking</option><option value="coverage">Skill coverage</option><option value="name">Filename A–Z</option></select><div className="view-switch"><button aria-label="Card view" aria-pressed={display==='cards'} className={display==='cards'?'active':''} onClick={()=>setDisplay('cards')}><Icon name="grid" size={17}/></button><button aria-label="Table view" aria-pressed={display==='table'} className={display==='table'?'active':''} onClick={()=>setDisplay('table')}><Icon name="menu" size={17}/></button></div></div>
    <div className="results-meta"><span>{visible.length} candidates shown</span><span>Ordered by {sort==='rank'?(results.method==='semantic'?'text similarity':'skill coverage'):sort==='coverage'?'skill coverage':'filename'}</span></div>
    {visible.length===0?<div className="empty-state"><Icon name="search" size={30}/><h3>{view==='shortlist'?'No shortlisted candidates match these filters':'No candidates match these filters'}</h3><p>Adjust your filters or add candidates to your shortlist.</p></div>:display==='cards'?<div className="candidate-grid">{visible.map(r=><article className="candidate-card" key={r.id}><div className="candidate-top"><div className="candidate-avatar">{r.name[0].toUpperCase()}</div><span className="rank">#{candidates.findIndex(c=>c.id===r.id)+1} in batch</span><button className={'icon-button shortlist-button '+(shortlist.includes(r.id)?'saved':'')} aria-label={(shortlist.includes(r.id)?'Remove from':'Add to')+' shortlist: '+r.name} aria-pressed={shortlist.includes(r.id)} onClick={()=>toggleShortlist(r.id)}><Icon name="star"/></button></div><h3 title={r.name}>{r.name}</h3><div className="score-row"><div><strong>{r.coverage==null?'—':r.coverage+'%'} </strong><span>skill coverage</span></div><span className="score-fraction">{r.matched.length}/{results.required.length} skills</span></div><div className="score-track"><span style={{width:(r.coverage??0)+'%'}}/></div>{r.semantic!=null&&<div className="semantic-label">Text similarity <b>{r.semantic}%</b></div>}<div className="card-skills"><span className="mini-label">MATCHED REQUIREMENTS</span><Tags items={r.matched.slice(0,5)}/>{r.matched.length>5&&<small className="muted">+{r.matched.length-5} more</small>}</div><div className="card-bottom"><span>{r.missing.length} skills to verify</span><button className="text-button" onClick={()=>setSelected(r.id)}>View evidence<Icon name="arrow" size={15}/></button></div></article>)}</div>:<div className="table-wrap"><table><thead><tr><th>Resume</th><th>Coverage</th><th>Text similarity</th><th>Matched</th><th>To verify</th><th>Shortlist</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><button className="text-button" onClick={()=>setSelected(r.id)}>{r.name}</button></td><td>{r.coverage==null?'—':r.coverage+'%'}</td><td>{r.semantic==null?'—':r.semantic+'%'}</td><td>{r.matched.length}</td><td>{r.missing.length}</td><td><input type="checkbox" aria-label={'Shortlist '+r.name} checked={shortlist.includes(r.id)} onChange={()=>toggleShortlist(r.id)}/></td></tr>)}</tbody></table></div>}</>:<div className="empty-state"><span className="empty-icon"><Icon name="doc" size={32}/></span><h3>Your next shortlist starts here</h3><p>Define the role and upload resumes to see skill coverage,<br/>candidate evidence, and your comparison results.</p><div className="empty-tags"><span>Skill coverage</span><span>Resume evidence</span><span>Easy exports</span></div></div>}
    </section>
    <footer>Resume Studio <span>·</span> A workspace for thoughtful candidate review.<p>Missing skills mean a term wasn’t detected. Similarity scores are not hiring probabilities. Review source evidence before making a decision.</p></footer>
   </main>
   {selectedRow&&<EvidenceDialog row={selectedRow} saved={shortlist.includes(selectedRow.id)} onToggle={()=>toggleShortlist(selectedRow.id)} onClose={()=>setSelected(null)}/>}
 </div>;
}

function EvidenceDialog({row,saved,onToggle,onClose}){
 const dialog=useRef(null);
 React.useEffect(()=>{const node=dialog.current;node.showModal();return()=>{node.close();};},[]);
 return <dialog ref={dialog} className="evidence-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="dialog-header"><div><span className="eyebrow">CANDIDATE EVIDENCE</span><h2>{row.name}</h2></div><button className="icon-button" aria-label="Close evidence" onClick={onClose}><Icon name="close"/></button></div><div className="dialog-content"><div className="evidence-scores"><div><span>Skill coverage</span><strong>{row.coverage==null?'—':row.coverage+'%'}</strong></div><div><span>Text similarity</span><strong>{row.semantic==null?'Not computed':row.semantic+'%'}</strong></div></div><h3>Matched requirements</h3><Tags items={row.matched}/><h3>Requirements to verify</h3><Tags items={row.missing} missing/><h3>Extracted resume text</h3><pre className="resume-text">{row.text}</pre><p className="muted">A keyword match does not establish proficiency. Use the resume text to verify context.</p></div><div className="dialog-footer"><button className="primary-button" onClick={onToggle}><Icon name="star" size={17}/>{saved?'Remove from shortlist':'Add to shortlist'}</button><button className="secondary-button" onClick={onClose}>Done</button></div></dialog>;
}
