[theme]
base = "dark"
primaryColor = "#9D83FF"
backgroundColor = "#0B1020"
secondaryBackgroundColor = "#151C31"
textColor = "#EEF2FF"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
